samplesheet:     "config/samplesheet.json"
basecall_config: "dna_r9.4.1_450bps_sup.cfg"

containers:
  base:     "docker://bash:5.1"
  python:   "docker://python:3.10.4-slim-bullseye"
  guppy:    "docker://quay.io/mbhall88/guppy-gpu:6.3.2"
  rs_utils: "docker://quay.io/mbhall88/rs-utils:0.1.0"